[build]
  # Directory to change to before starting build
  base = "client/"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "build/"
  
  # Default build command
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://saltrenewal.onrender.com/api"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
